// Generated by CoffeeScript 1.6.2
(function() {
  $.fn.extend({
    expList: function(options) {
      var opts, self;

      self = $.fn.expList;
      opts = $.extend({}, self.default_options, options);
      return $(this).each(function(i, elem) {
        self.init(elem, opts);
        if (opts.log) {
          return self.log(elem);
        }
      });
    }
  });

  $.extend($.fn.expList, {
    default_options: {
      log: true,
      duration: 600
    },
    init: function(elem, opts) {
      var child, childrenList, _i, _len, _results;

      $(elem).find('ul').hide();
      childrenList = $(elem).find('li:has(ul)');
      _results = [];
      for (_i = 0, _len = childrenList.length; _i < _len; _i++) {
        child = childrenList[_i];
        _results.push((function() {
          return $(child).click(function(e) {
            $(e.target).closest('li').children('ul').toggle(opts.duration);
            return e.stopPropagation();
          });
        })());
      }
      return _results;
    }
  });

}).call(this);
